version: '3.7'
services:
  bareos-dir:
    image: barcus/bareos-director:latest
    volumes:
      - director_config:/etc/bareos
      - director_data:/var/lib/bareos # required for MyCatalog backup
    environment:
      - DB_HOST=bareos-db
      - DB_PORT=3306
      - DB_PASSWORD=passwd
      - DB_NAME=bareos
      - DB_USER=root
      - BAREOS_SD_HOST=bareos-sd
      - BAREOS_SD_PASSWORD=passwd
      - BAREOS_FD_HOST=bareos-fd
      - BAREOS_FD_PASSWORD=passwd
      - BAREOS_WEBUI_PASSWORD=passwd
      - SMTP_HOST=smtpd
      - ADMIN_MAIL=your@mail.address # Change me!
    depends_on:
      - bareos-db

  bareos-sd:
    image: barcus/bareos-storage:latest
    ports:
      - 9103:9103
    volumes:
      - storage_config:/etc/bareos
      - storage_data:/var/lib/bareos/archive
    environment:
      - BAREOS_SD_PASSWORD=passwd

  bareos-fd:
    image: barcus/bareos-client:latest
    volumes:
      - client_config:/etc/bareos
      - director_data:/var/lib/bareos-director # required for MyCatalog backup
    environment:
      - BAREOS_FD_PASSWORD=passwd

  bareos-webui:
    image: barcus/bareos-webui:latest
    ports:
      - 8080:9100
    environment:
      - BAREOS_DIR_HOST=bareos-dir
      - PHP_FPM_HOST=php-fpm
      - PHP_FPM_PORT=9000
    volumes:
      - webui_config:/etc/bareos-webui
      - webui_data:/usr/share/bareos-webui
    depends_on:
      - php-fpm

  php-fpm:
    image: barcus/php-fpm-alpine
    volumes:
      - webui_config:/etc/bareos-webui
      - webui_data:/usr/share/bareos-webui

  bareos-db:
    image: mysql:5.6
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd

  smtpd:
    image: namshi/smtp

volumes:
  director_config:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/config/director'
  director_data:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/data/director'
  storage_config:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/config/storage'
  storage_data:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/data/storage'
  client_config:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/config/client'
  webui_config:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/config/webui'
  webui_data:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/bareos/data/webui'
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: 'bind'
      device: '/data/mysql/data'
